### ISSUE TITLE
Not all routes are protectected

### ISSUE THREAD

**Issue by mathias22osterhagen22** [HrithikMittal/Loopback4-auth#2]
you add at the end of your readme than with this lines : 
```ts
 security: [
        {
          // secure all endpoints with 'jwt'
          jwt: [],
        },
      ],
```

It secure all the endpoint but in fact it just add a lock icon in the API explorer. 
You can still make the requests without giving a token.
Did I miss something ?
It's mandatory in the end to add ` @authenticate("jwt")` in all routes in all routes.

**Comment by HrithikMittal** [comment]
Ya you can secure the routes bypassing here also in the jwt array 
but it is highly advisable to add separate authenticate decorator because you can letter on adding the authorization.
and you are right that
```
 security: [
        {
          // secure all endpoints with 'jwt'
          jwt: [],
        },
      ],
```
will not make authenticate you have to add the routes in the array.

I am also trying these all pieces of stuff from the loopback4 docs which are very hard to understand.

**Comment by mathias22osterhagen22** [comment]
Yes ok, it's what I understood in the end.

Thank you, yes I pass through a lot of documentation during my career and to be honest this one is one of the worst I read.

Difficult to understand something when there are errors inside the explanation.

**Comment by HrithikMittal** [comment]
Ya, you are right there docs is the worst. But here I am developing to help others. Please do share with others to and star this repo
